version: "3.7"

networks:
  default:
    external:
      name: cloudbuild
  odoonet:

volumes:
  odoo-data:
  odoo-testlogs:
  psql:

services:
  odoo:
    image: iterativodo/dockerdoo:${ODOO_VERSION}
    env_file: .env

    environment:
      - WDB_SOCKET_SERVER=wdb
      - WDB_NO_BROWSER_AUTO_OPEN=True
      - WDB_WEB_PORT=1984
      - LOG_LEVEL=debug

    restart: unless-stopped

    ports: ["8069:8069", "8072:8072"]

    volumes:
      # Host paths (addons & conf)
      - ./custom:${ODOO_EXTRA_ADDONS}:delegated
      - ./config/odoo.conf:/etc/odoo/odoo.conf:cached
      - ./src/odoo:/${ODOO_BASEPATH}:cached
      # Named volumes
      - odoo-data:${ODOO_DATA_DIR}
      - odoo-testlogs:${ODOO_LOGS_DIR}

    command: 
      [
        "odoo",
        "--dev", "wdb,reload,qweb,werkzeug,xml"
      ]
    depends_on: ["db", "wdb"]

    networks:
      odoonet:
  # ------------------------
  db:
    image: postgres:${PSQL_VERSION}-alpine
    restart: unless-stopped
    volumes:
      - psql:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      odoonet:
  # ------------------------
  wdb:
    image: kozea/wdb:3.3.0
    ports: ["1984:1984"]
    restart: unless-stopped
    networks:
      odoonet:
    depends_on: ["db"]
